In [1]:
import torch
from torch import nn

In [2]:
linear = nn.Linear(20,30)

In [12]:
low = torch.randn(20)
high = torch.randn(20)

In [14]:
slope = high/(high-low+1e-6)

In [18]:
(low*high)/(high-low)

tensor([-0.4020, -0.6891, -1.2891,  0.3549, -0.2554,  0.9364,  5.1451,  0.5793,
         0.3101, -0.1773,  0.7926,  1.5253, -0.7221,  0.6011,  0.1321,  3.5054,
         0.3323,  0.5848, -0.2758,  0.1128])

In [4]:
linear(low) == torch.matmul(linear.weight, low) + linear.bias

tensor([True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True])

In [19]:
a = list(range(10))

In [22]:
for i in a[-10:]:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [25]:
b = []
b +=[low]

In [28]:
raise Exception("Wrong")

Exception: Wrong

In [14]:
# if the weight is negative we need to use the high, not the low to obtain the bound 

In [15]:
W = linear.weight

In [ ]:
for w in W: 
    print(w)

In [18]:
w.size()

torch.Size([20])

In [27]:
mask_high = (w<0).int()
mask_low = (w>=0).int()

In [28]:
mask_low*low+ mask_high*low == low

tensor([True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True])

In [32]:
torch.zeros(w.size()[0])

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
w.size()[0]

20

In [33]:
torch.matmul(w, low)

tensor(-0.6701, grad_fn=<DotBackward>)

In [43]:
type(linear) == torch.nn.Linear

True

In [47]:
a, b, c = 0, 0 , 0