# Launch verifier

In [ ]:
!  code/verifier.py --net fc1 --spec ../test_cases/fc1/img0_0.06200.txt

---
# Play around

In [1]:
import torch
from torch import nn

In [17]:
linear = nn.Linear(20,30)

In [2]:
low = torch.randn(20)
high = torch.randn(20)

In [16]:
if (low[2]>0 or high[2]<0): print("Ciao")

Ciao


In [14]:
b = torch.tensor(range(10))

In [26]:
if sum((b[9]>b).int())==9: print("bye")

bye


In [4]:
slope = high/(high-low+1e-6)

In [5]:
(low*high)/(high-low)

tensor([-0.0753,  1.3890,  0.7015, -3.2208,  0.4761, -0.1447,  1.1150,  2.4698,
        -0.1191, -0.3385, -0.1453,  0.3893,  0.7234,  2.9901, -1.5413, -1.1846,
        -0.5396,  0.1447,  0.1042, -0.3267])

In [6]:
linear(low) == torch.matmul(linear.weight, low) + linear.bias

tensor([True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True])

In [19]:
a = list(range(10))

In [22]:
for i in a[-10:]:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [25]:
b = []
b +=[low]

In [28]:
raise Exception("Wrong")

Exception: Wrong

In [14]:
# if the weight is negative we need to use the high, not the low to obtain the bound 

In [18]:
W = linear.weight

In [ ]:
for w in W: 
    print(w)

In [18]:
w.size()

torch.Size([20])

In [20]:
mask_high = (w<0).int()
mask_low = (w>=0).int()

In [22]:
mask_low

tensor([1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1],
       dtype=torch.int32)

In [28]:
mask_low*low+ mask_high*low == low

tensor([True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True])

In [32]:
torch.zeros(w.size()[0])

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
w.size()[0]

20

In [33]:
torch.matmul(w, low)

tensor(-0.6701, grad_fn=<DotBackward>)

In [43]:
type(linear) == torch.nn.Linear

True

In [47]:
a, b, c = 0, 0 , 0

In [31]:
b = torch.eye(9,10)*-1

In [34]:
b[:,3]=1

In [37]:
a = torch.eye(10,8)

In [50]:
b = torch.zeros(9) +1

In [51]:
b.numpy().all()>0

True

In [3]:
t = torch.ones((1,1,28,28))

In [5]:
f = nn.Flatten()

In [13]:
f(t).squeeze()[4]

tensor(1.)

In [54]:
mm = torch.eye(9)*(-1)

In [55]:
n = 4
c = 10

In [56]:
torch.cat([mm[:,0:n],torch.ones(c-1,1),mm[:,n:c]],1)

tensor([[-1., -0., -0., -0.,  1., -0., -0., -0., -0., -0.],
        [-0., -1., -0., -0.,  1., -0., -0., -0., -0., -0.],
        [-0., -0., -1., -0.,  1., -0., -0., -0., -0., -0.],
        [-0., -0., -0., -1.,  1., -0., -0., -0., -0., -0.],
        [-0., -0., -0., -0.,  1., -1., -0., -0., -0., -0.],
        [-0., -0., -0., -0.,  1., -0., -1., -0., -0., -0.],
        [-0., -0., -0., -0.,  1., -0., -0., -1., -0., -0.],
        [-0., -0., -0., -0.,  1., -0., -0., -0., -1., -0.],
        [-0., -0., -0., -0.,  1., -0., -0., -0., -0., -1.]])

In [30]:
mm[:,1] = 1

In [34]:
mm

tensor([[-1, -1,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0, -1,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0, -1,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0, -1,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0, -1,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0, -1,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0, -1,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0, -1,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0, -1]])