# Launch verifier

In [6]:
!  code/verifier.py --net fc1 --spec ../test_cases/fc1/img0_0.06200.txt

---
# Play around

In [7]:
import torch
from torch import nn

In [8]:
linear = nn.Linear(20,30)

In [9]:
low = torch.randn(20)
high = torch.randn(20)

In [10]:
if (low[2]>0 or high[2]<0): print("Ciao")

Ciao


In [11]:
b = torch.tensor(range(10))

In [12]:
if sum((b[9]>b).int())==9: print("bye")

bye


In [13]:
slope = high/(high-low+1e-6)

In [14]:
(low*high)/(high-low)

tensor([ 0.3757,  0.1847,  0.3286,  0.0281,  0.0796, -0.1315, -0.3567,  0.5412,
         3.3045, -0.2847, -7.8086,  9.1827, -0.1897, -3.4624, -3.2016, -0.4401,
        -0.6775, -0.1525,  1.5915,  0.4968])

In [15]:
linear(low) == torch.matmul(linear.weight, low) + linear.bias

tensor([True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True])

In [16]:
a = list(range(10))

In [17]:
for i in a[-10:]:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [18]:
b = []
b +=[low]

In [19]:
raise Exception("Wrong")

Exception: Wrong

In [20]:
# if the weight is negative we need to use the high, not the low to obtain the bound 

In [21]:
W = linear.weight

In [48]:
linear.weights

ModuleAttributeError: 'Linear' object has no attribute 'weights'

In [22]:
for w in W: 
    print(w)

tensor([-0.0558,  0.0158, -0.1341,  0.1626, -0.0597,  0.1036, -0.0944, -0.0719,
        -0.2125,  0.1777, -0.2232, -0.1800,  0.0116, -0.1082, -0.0118, -0.1463,
        -0.0617, -0.0626, -0.1268,  0.0666], grad_fn=<UnbindBackward>)
tensor([ 0.0147,  0.1199, -0.0593, -0.1118, -0.1764, -0.1687,  0.1288, -0.1503,
         0.0783, -0.1326,  0.1362,  0.2211,  0.1578, -0.2030,  0.1177, -0.0703,
         0.2056,  0.0665,  0.1757, -0.0239], grad_fn=<UnbindBackward>)
tensor([-0.1869,  0.1830,  0.1869, -0.1717,  0.0445,  0.0641, -0.1594, -0.1314,
         0.2000,  0.0184,  0.0527,  0.0838,  0.0467, -0.1228,  0.1430, -0.0104,
         0.2204,  0.1752, -0.1517,  0.1391], grad_fn=<UnbindBackward>)
tensor([ 0.0695, -0.1829,  0.0295,  0.0978,  0.0731, -0.1585, -0.0772, -0.0126,
         0.1225, -0.0426, -0.1674, -0.0967,  0.0584, -0.1384, -0.0300,  0.1834,
        -0.1476,  0.1262,  0.1966, -0.0284], grad_fn=<UnbindBackward>)
tensor([ 0.1247,  0.0291,  0.1527, -0.1003, -0.2017,  0.0979, -0.1391, -0.17

In [23]:
w.size()

torch.Size([20])

In [24]:
mask_high = (w<0).int()
mask_low = (w>=0).int()

In [25]:
mask_low

tensor([0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1],
       dtype=torch.int32)

In [26]:
mask_low*low+ mask_high*low == low

tensor([True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True])

In [27]:
torch.zeros(w.size()[0])

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [28]:
w.size()[0]

20

In [29]:
torch.matmul(w, low)

tensor(0.4045, grad_fn=<DotBackward>)

In [30]:
type(linear) == torch.nn.Linear

True

In [31]:
a, b, c = 0, 0 , 0

In [43]:
b = torch.eye(20,20)
for i in range(20): b[i,i] = -1

In [46]:
b2 =  torch.eye(20,20)*(-1)

In [47]:
torch.matmul(W,b) == torch.matmul(W,b2)

tensor([[True, True, True, True, True, True, True, True, True, True, True, True,
         True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True, True, True,
         True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True, True, True,
         True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True, True, True,
         True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True, True, True,
         True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True, True, True,
         True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True, True, True,
         True, True, True, True, True, True, True, True],
        [True, True, True, 

In [42]:
W

Parameter containing:
tensor([[-0.0558,  0.0158, -0.1341,  0.1626, -0.0597,  0.1036, -0.0944, -0.0719,
         -0.2125,  0.1777, -0.2232, -0.1800,  0.0116, -0.1082, -0.0118, -0.1463,
         -0.0617, -0.0626, -0.1268,  0.0666],
        [ 0.0147,  0.1199, -0.0593, -0.1118, -0.1764, -0.1687,  0.1288, -0.1503,
          0.0783, -0.1326,  0.1362,  0.2211,  0.1578, -0.2030,  0.1177, -0.0703,
          0.2056,  0.0665,  0.1757, -0.0239],
        [-0.1869,  0.1830,  0.1869, -0.1717,  0.0445,  0.0641, -0.1594, -0.1314,
          0.2000,  0.0184,  0.0527,  0.0838,  0.0467, -0.1228,  0.1430, -0.0104,
          0.2204,  0.1752, -0.1517,  0.1391],
        [ 0.0695, -0.1829,  0.0295,  0.0978,  0.0731, -0.1585, -0.0772, -0.0126,
          0.1225, -0.0426, -0.1674, -0.0967,  0.0584, -0.1384, -0.0300,  0.1834,
         -0.1476,  0.1262,  0.1966, -0.0284],
        [ 0.1247,  0.0291,  0.1527, -0.1003, -0.2017,  0.0979, -0.1391, -0.1740,
          0.2112, -0.1550, -0.1281, -0.1582,  0.1640, -0.1642,  0

In [ ]:
b[:,3]=1

In [ ]:
a = torch.eye(10,8)

In [ ]:
b = torch.zeros(9) +1

In [ ]:
b.numpy().all()>0

In [ ]:
t = torch.ones((1,1,28,28))

In [ ]:
f = nn.Flatten()

In [ ]:
f(t).squeeze()[4]

In [ ]:
mm = torch.eye(9)*(-1)

In [ ]:
n = 4
c = 10

In [ ]:
torch.cat([mm[:,0:n],torch.ones(c-1,1),mm[:,n:c]],1)

In [ ]:
mm[:,1] = 1

In [ ]:
mm