In [2]:
import torch
from torch import nn

In [3]:
linear = nn.Linear(20,30)

In [4]:
low = torch.randn(20)

In [12]:
linear(low) == torch.matmul(linear.weight, low) + linear.bias

tensor([True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True])

In [14]:
# if the weight is negative we need to use the high, not the low to obtain the bound 

In [15]:
W = linear.weight

In [ ]:
for w in W: 
    print(w)

In [18]:
w.size()

torch.Size([20])

In [27]:
mask_high = (w<0).int()
mask_low = (w>=0).int()

In [28]:
mask_low*low+ mask_high*low == low

tensor([True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True])

In [32]:
torch.zeros(w.size()[0])

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
w.size()[0]

20

In [33]:
torch.matmul(w, low)

tensor(-0.6701, grad_fn=<DotBackward>)

In [43]:
type(linear) == torch.nn.Linear

True

In [47]:
a, b, c = 0, 0 , 0